blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/website/urls.py
from django.urls import path, include
from .views import hello_blog
from .views import post_detail, save_form




app_name = 'blog'

urlpatterns = [
    path('', hello_blog, name='home'),
    path('post/<int:id>/', post_detail, name='post_detail'),
    path('save-form/', save_form, name='save_form'),
] 

blog/website/models.py
from django.db import models
from django.db.models.fields import CharField

# Create your models here.


class Categories(models.TextChoices):
    tech = 'TC', 'Tecnologia'
    curiosity = 'CR', 'Curiosidades'
    gr = 'GR', 'Geral'

class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200)
    content = models.TextField()

    categories = models.CharField(
        max_length=2,
        choices=Categories.choices,
        default=Categories.gr,
    )

    deleted = models.BooleanField(default=True)
    image = models.ImageField(upload_to='posts', null=True, blank=True)

    def __str__(self):
        return self.title

    def full_name(self):
        return self.title + ' ' + self.sub_title

    def get_categories_label(self):
        return self.get_categories_display()

    full_name.admin_order_field = 'title'

blog/website/views.py
from django.shortcuts import render
from .models import Post, Contact

# Create your views here.


def hello_blog(request):
    lista_post = Post.objects.filter(deleted=False)
    data = {"posts": lista_post}
    return render(request, 'index.html', data)


def post_detail(request, id):
    post = Post.objects.get(id=id)
    data = {"post": post}
    return render(request, 'post_detail.html', data)


def save_form(request):
    name  = request.POST['name']
    Contact.objects.create(
        name=name,
        email=request.POST['email'],
        message=request.POST['message']
    )
    data = {"name": name}
    return render(request, 'contact.html', data)

blog/website/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Strata by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html lang="pt-br">

<head>
    <title>Python Garden</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
</head>

<body class="is-preload">

    <!-- Header -->
    <header id="header">
        <div class="inner">
            <a href="{% url 'blog:home' %}" class="image avatar"><img src="{% static 'images/avatar.jpg' %}"
                    alt="" /></a>
            <h1><strong>Alan Santos</strong></h1>
            Curso simplificado python e Django 3, deploy na nuvem com
            Google App Engine
        </div>
    </header>

    <!-- Main -->
    <div id="main">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                <li><a href="https://twitter.com/alan_d3v" target="_blank" class="icon brands fa-twitter"><span
                            class="label">Twitter</span></a></li>
                <li><a href="https://github.com/alan-d3v" target="_blank" class="icon brands fa-github"><span
                            class="label">Github</span></a></li>
                <li><a href="https://www.linkedin.com/in/alan-sso/" target="_blank"
                        class="icon brands fa-linkedin"><span class="label">Github</span></a></li>
                <li><a href="https://www.facebook.com/profile.php?id=100038344988682" target="_blank"
                        class="icon brands fa-facebook"><span class="label">Github</span></a></li>


            </ul>
            <ul class="copyright">
                <li>&copy; Untitled</li>
                <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.poptrox.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

blog/website/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ name }} seu contato foi recebido com sucesso.</h2>

<a href="{% url 'blog:home' %}" class="button">Inicio</a>


{% endblock content %}

blog/website/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- One -->
<section id="one">
	<header class="major">
		<h2>Python Garden</h2>
	</header>
	<p>Criei este blog para registrar minha aprendizagem no uso da linguagem de programação Python e seus
		diversos frameworks. Os frameworks são importantíssimos, pois seu objetivo é fornecer ferramentas para
		facilitar o desenvolvimento de um determinado projeto em uma base estável.</p>
</section>

<!-- Two -->
<section id="two">
	<h2>Posts</h2>
	<div class="row">
		{% for post in posts %}
		<article class="col-6 col-12-xsmall work-item">
			{% if post.image %}
				<a href="{{ post.image.url }}" class="image fit thumb"><img src="{{ post.image.url }}" alt="" /></a>
			{% else %}
				<a href="{% static 'images/fulls/01.jpg' %}" class="image fit thumb"><img
					src="{% static 'images/thumbs/01.jpg' %}" alt="" /></a>

			{% endif %}
				<h3>{{ post.title }}</h3>
				<p>{{ post.sub_title }}</p>
				<span>{{ post.get_categories_label }}</span>

			<ul class="actions">
				<li><a href="{% url 'blog:post_detail'  post.id %}" class="button">Leia Mais</a></li>
			</ul>
		</article>
		{% endfor %}

	</div>
</section>

<!-- Three -->
<section id="three">
	<h2>Get In Touch</h2>
	<p>Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu
		lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor.</p>
	<div class="row">
		<div class="col-8 col-12-small">
			<form method="post" action="{% url 'blog:save_form' %}">
				{% csrf_token %}
				<div class="row gtr-uniform gtr-50">
					<div class="col-6 col-12-xsmall"><input type="text" name="name" id="name" placeholder="Name" />
					</div>
					<div class="col-6 col-12-xsmall"><input type="email" name="email" id="email" placeholder="Email" />
					</div>
					<div class="col-12"><textarea name="message" id="message" placeholder="Message" rows="4"></textarea>
					</div>
				</div>
				<ul class="actions">
					<li><input type="submit" value="Send Message" /></li>
				</ul>
			</form>
			
		</div>
		<div class="col-4 col-12-small">
			<ul class="labeled-icons">
				<li>
					<h3 class="icon solid fa-home"><span class="label">Address</span></h3>
					1234 Somewhere Rd.<br />
					Nashville, TN 00000<br />
					United States
				</li>
				<li>
					<h3 class="icon solid fa-mobile-alt"><span class="label">Phone</span></h3>
					000-000-0000
				</li>
				<li>
					<h3 class="icon solid fa-envelope"><span class="label">Email</span></h3>
					<a href="#">hello@untitled.tld</a>
				</li>
			</ul>
		</div>
	</div>
</section>

{% endblock content %}

blog/website/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/post_detail.css' %}" />

<h3>{{ post.title }}</h3>
<p>{{ post.sub_title }}</p>
<span>{{ post.get_categories_label }}</span>
<div class="detail-image">
    <img src="{{ post.image.url }}" alt="post_image">
</div>

<p>{{ post.content }}</p>

<ul class="actions">
    <li><a href="{% url 'blog:home' %}" class="button">Voltar</a></li>
</ul>

{% endblock content %}